"""empty message

Revision ID: 1488d90762b2
Revises: 1e8b647e09e8
Create Date: 2019-05-06 16:39:15.971534

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1488d90762b2'
down_revision = '1e8b647e09e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Comment', sa.Column('accountId', sa.Integer(), nullable=False))
    op.add_column('Comment', sa.Column('body', sa.String(), nullable=False))
    op.add_column('Comment', sa.Column('modified', sa.Boolean(), server_default='false', nullable=True))
    op.add_column('Comment', sa.Column('timeCreated', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('Comment', sa.Column('timeModified', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.drop_constraint('Comment_parentCommentId_fkey', 'Comment', type_='foreignkey')
    op.create_foreign_key(None, 'Comment', 'Account', ['accountId'], ['id'])
    op.drop_column('Comment', 'description')
    op.drop_column('Comment', 'title')
    op.drop_column('Comment', 'parentCommentId')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Comment', sa.Column('parentCommentId', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('Comment', sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('Comment', sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'Comment', type_='foreignkey')
    op.create_foreign_key('Comment_parentCommentId_fkey', 'Comment', 'Comment', ['parentCommentId'], ['id'])
    op.drop_column('Comment', 'timeModified')
    op.drop_column('Comment', 'timeCreated')
    op.drop_column('Comment', 'modified')
    op.drop_column('Comment', 'body')
    op.drop_column('Comment', 'accountId')
    # ### end Alembic commands ###
